exports.authActionTypes = {
    SIGNUP_REQUEST:"SIGNUP_REQUEST",
    SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
    SIGNIN_REQUEST: "SIGNIN_REQUEST",
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    SIGNIN_FAILURE: "SIGNIN_FAILURE"

}
exports.categoryActionTypes = {
    ADD_CATEGORY_REQUEST : 'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS : 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAILURE : 'ADD_CATEGORY_FAILURE',
    GET_ALL_CATEGORIES_REQUEST : 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS : 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE : 'GET_ALL_CATEGORIES_FAILURE'
}

exports.foodActionTypes ={
    ADD_FOOD_REQUEST : 'ADD_FOOD_REQUEST',
    ADD_FOOD_SUCCESS : 'ADD_FOOD_SUCCESS',
    ADD_FOOD_FAILURE : 'ADD_FOOD_FAILURE',

    GET_FOOD_REQUEST: 'GET_FOOD_REQUEST',
    GET_FOOD_SUCCESS:'GET_FOOD_SUCCESS',
    GET_FOOD_FAILURE:'GET_FOOD_FAILURE'
}
